# Example config for Weather MLOps Pipeline
# Copy to config.yaml and fill in your own API key and settings
api:
  key: "your-api-key-here"
  base_url: "http://api.openweathermap.org/data/2.5/weather"
  zipcode: "02920"
  city: "Cranston"
  state: "RI"
  country: "United States"
  latitude: "41.7798"
  longitude: "-71.4373"
  units: "metric"
  country_code: "US"
  timezone: "America/New_York"
  max_samples: 100
  sample_interval: 30
data:
  raw_path: "data/raw/weather_raw.json"
  processed_path: "data/processed/weather_clean.csv"
model:
  path: "data/models/weather_model.pkl" 